### ISSUE TITLE
Automated participants list

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2015#10]
Ginger requested: I'm under the impression that there isn't yet a method in the new site for automating the "Participants" list.

Actually this has been worked on, Ale created a "view" for those entries: 
http://libregraphicsmeeting.org/2015/wp/wp-admin/post.php?post=363&action=edit

And ginger has created a page that uses this view with the shortcode: [display-frm-data id=participants]

http://libregraphicsmeeting.org/2015/participants/

I'm going to improve it by adding the CSS for columns, as used in 2014: http://libregraphicsmeeting.org/2014/participants/

**Comment by aoloe** [comment]
this is the workflow when mailing list, private mails and issue tracker mix up :-)
we only miss louis having asked for the participants list, iirc...

thanks for summarizing it up and creating the ticket!
