### ISSUE TITLE
on-call duty durin the lgm

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/htdocs-2015#12]
question: is anybody from the infrastructure team around during the LGM?

**Comment by aoloe** [comment]
personally, i will be in vienna and i cannot promise that i will be able to do much if there are any urgence concerning the website...

**Comment by ms-studio** [comment]
I will be available to look after any website issues during those days.

**Comment by aoloe** [comment]
perferct i'll be around until thursday afternoon...
