### ISSUE TITLE
the entries in formidable forms don't show up anymore

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/htdocs-2015#13]
the views for the participants and for the program still work, but the form entries cannot be edited anymore.
when i (and ginger and femke) go to the form, an empty list is displayed.

does anybody have a clue what is happening?

**Comment by ms-studio** [comment]
Might be linked to the recent version upgrade of WordPress ?
Didn't see that issue on other sites using Formidable.

There's an update available for Formidable, from 1.07.11 to 2.0.04. I think we should apply it.

**Comment by ms-studio** [comment]
So, it looks like the update helped: 
The entries are displaying again.
