### ISSUE TITLE
Make website multilingual

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2015#5]
Request by Louis:

> I wonder what the procedure would be to have a French version of our website (with a language link).
> 
> I believe we must have some sort of plug-in already installed because it’s not the first time we need to have a bilingual website (or multilingual even!).
> 
> Can someone in charge of the under-the-hood mechanics make that happen? I’ll cover the over-the-hood part!

**Comment by ms-studio** [comment]
Some solutions:

1) If we want to use a fully featured multilingual WordPress plugin, Polylang is a good candidate: 
https://wordpress.org/plugins/polylang/

2) Another option, if we want to keep things simple: 
- Create a custom taxonomy for language.
- Use posts-2-posts to "link" the translations (post-2-posts is the universally recommended plugin for post relationships).
- Apply some simple tweaks to the theme to make everything work.

**Comment by aoloe** [comment]
at a first sight, polylang looks good.

we should make sure that we know what will be translated:
- all the "static" pages? -> probably yes
- the program? probably not
- the blog posts? probably not

what do we have to do, to ensure that french speaking people have a good experience on the site?

the question is also, how many blog posts we will have... in the past we had only very few of them (max 10) but they were very prominent (decreasing the overall quality of the lgm site).

finally, having had a look at posts-to-posts, i think that in the future we should go for a more "posts" based wp (as an example by transforming the program in a list of posts!) but for this year i would go for the most comfortable way...

**Comment by ms-studio** [comment]
Good, I think polylang is a good choice then.
I'm installing it, so Louis can start translating.

**Comment by ms-studio** [comment]
Feedback from Elisa de Castro Guerra:

> I have a positive experience with the plugin polylang.  
> https://wordpress.org/plugins/polylang/  
> Easy to install, set up, understand, and use.

**Comment by aoloe** [comment]
manuel says:

Once the pages are translated, we can build the menu for the French version (under Appearance, Menus : Main Navigation French).

**Comment by aoloe** [comment]
we also need to switch the picture in the header.

according to https://wordpress.org/support/topic/plugin-polylang-changing-header-image-according-to-language we need to slightly change the template...

any further idea?

**Comment by ms-studio** [comment]
Yes, this needs a little change to the theme.  
I already did this previously, so I can simply copy my code from a previous project.
