### ISSUE TITLE
Database backups

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2015#6]
I just installed a plugin (BackWpUp) that will make weekly backups of the MySQL database. Just a good practice for securing the site content.

Doing that, I noticed it had trouble archiving the tables created by simple history. 
- The size of MySQL export _before_ cleaning Simple History: 81 Mb.
- The size of MySQL export _after_ cleaning the Simple History logs: 1.2 Mb.

So it appears that "Simple History" is keeping too much data. Didn't find a setting to make it keep less...

**Comment by aoloe** [comment]
on the one side, having a look at the simple history's dashboard widget looks somehow useful...

... on the other side, we have not used it until now...

if it's more hassle than it's good, just disable / remove it!

or, we could try to patch it to automatically clear all data that is older than 1 week (or so)... they accept pull requests...

**Comment by ms-studio** [comment]
It looks like the Simple History plugin includes a filter that allows to customize the duration: 

```
add_filter("simple_history_db_purge_days_interval", function($days) {
  $days = 10;
  return $days;
});
```

https://wordpress.org/support/topic/increase-60-days-limit-for-cleaning-database?replies=6#post-5194116

Will try that.

**Comment by ms-studio** [comment]
Indeed the fix is working, Simple History now only keeps the last 10 days.
